In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path = '/content/drive/MyDrive/Все оставшееся/Axenix/Факт_Производства.txt'

In [ ]:
data = pd.read_table(path, sep=',')
data.head()

,Номер заказа,Номер трубы,Время принятия на Электросварочный стан,Время принятия в Буфер,Время принятия на Кромкообрабатывающие станки,Время принятия в Буфер.1,Время принятия на Термообработку,Время принятия в Буфер.2,Время принятия на Испытания,Время принятия на Склад готовой продукции
0,135,15012396,01.03.2024 9:00,01.03.2024 17:50,01.03.2024 17:56,01.03.2024 20:26,01.03.2024 20:34,01.03.2024 22:34,01.03.2024 22:41,02.03.2024 0:52
1,135,15012403,01.03.2024 9:01,01.03.2024 17:51,01.03.2024 17:57,01.03.2024 20:27,01.03.2024 20:35,01.03.2024 22:35,01.03.2024 22:42,02.03.2024 0:53
2,135,15012410,01.03.2024 9:02,01.03.2024 17:52,01.03.2024 17:57,01.03.2024 20:27,01.03.2024 20:37,01.03.2024 22:36,01.03.2024 22:42,02.03.2024 0:54
3,135,15012417,01.03.2024 9:03,01.03.2024 17:53,01.03.2024 17:58,01.03.2024 20:28,01.03.2024 20:38,01.03.2024 22:38,01.03.2024 22:43,02.03.2024 0:55
4,135,15012424,01.03.2024 9:04,01.03.2024 17:54,01.03.2024 17:59,01.03.2024 20:29,01.03.2024 20:39,15.03.2024 22:39,01.03.2024 22:44,02.03.2024 0:56

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15506 entries, 0 to 15505
Data columns (total 10 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Номер заказа                                    15506 non-null  int64
 1    Номер трубы                                    15506 non-null  int64
 2    Время принятия на Электросварочный стан        15506 non-null  object
 3    Время принятия в Буфер                         15506 non-null  object
 4    Время принятия на Кромкообрабатывающие станки  15506 non-null  object
 5    Время принятия в Буфер.1                       15506 non-null  object
 6    Время принятия на Термообработку               15506 non-null  object
 7    Время принятия в Буфер.2                       15506 non-null  object
 8    Время принятия на Испытания                    15506 non-null  object
 9    Время принятия на Склад готовой продукции      15506 non-null  object
dtypes: int64(2), object(8)
memory usage: 1.2+ MB

In [ ]:
columns = data.columns[2:]

In [ ]:
data.head()

display(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15506 entries, 0 to 15505
Data columns (total 10 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Номер заказа                                    15506 non-null  int64
 1    Номер трубы                                    15506 non-null  int64
 2    Время принятия на Электросварочный стан        15506 non-null  object
 3    Время принятия в Буфер                         15506 non-null  object
 4    Время принятия на Кромкообрабатывающие станки  15506 non-null  object
 5    Время принятия в Буфер.1                       15506 non-null  object
 6    Время принятия на Термообработку               15506 non-null  object
 7    Время принятия в Буфер.2                       15506 non-null  object
 8    Время принятия на Испытания                    15506 non-null  object
 9    Время принятия на Склад готовой продукции      15506 non-null  object
dtypes: int64(2), object(8)
memory usage: 1.2+ MB

None

In [ ]:
for col in columns:
  data[col] = pd.to_datetime(data[col], format=' %d.%m.%Y %H:%M')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15506 entries, 0 to 15505
Data columns (total 10 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Номер заказа                                    15506 non-null  int64
 1    Номер трубы                                    15506 non-null  int64
 2    Время принятия на Электросварочный стан        15506 non-null  datetime64[ns]
 3    Время принятия в Буфер                         15506 non-null  datetime64[ns]
 4    Время принятия на Кромкообрабатывающие станки  15506 non-null  datetime64[ns]
 5    Время принятия в Буфер.1                       15506 non-null  datetime64[ns]
 6    Время принятия на Термообработку               15506 non-null  datetime64[ns]
 7    Время принятия в Буфер.2                       15506 non-null  datetime64[ns]
 8    Время принятия на Испытания                    15506 non-null  datetime64[ns]
 9    Время принятия на Склад готовой продукции      15506 non-null  datetime64[ns]
dtypes: datetime64[ns](8), int64(2)
memory usage: 1.2 MB

In [ ]:
data.to_excel('Факт производства с метками времени.xlsx', index=False)